#ifndef LOG4CPLUS_APPENDERSEXPORTS_H
#define LOG4CPLUS_APPENDERSEXPORTS_H

#include "log4cplus/config.hxx"

#if !defined(_WIN32)
  #if defined (INSIDE_LOG4CPLUS_APPENDERS)
    #define LOG4CPLUS_APPENDERS_EXPORT LOG4CPLUS_DECLSPEC_EXPORT
  #else
    #define LOG4CPLUS_APPENDERS_EXPORT LOG4CPLUS_DECLSPEC_IMPORT
  #endif // defined (INSIDE_LOG4CPLUS_APPENDERS)
#endif // !_WIN32

#endif // LOG4CPLUS_APPENDERSEXPORTS_H
